### ISSUE TITLE
bugs user connection is very short time ??

### ISSUE THREAD

**Issue by rawezhcode** [centrifugal/centrifuge-dart#89] opened 2024-09-06 23:01 UTC
I have a big problem, I don't know if the cause is in the server or this package.
My problem is when more than 2000 users join a subscription to one channel,
 In a very short time, it throws out most users within seconds.
 From 2000 users to 800~ users and less ?

**Comment by FZambia** [comment] 2024-09-07 04:02
Hello @rawezhcode 

This may be due to server OS limits - https://centrifugal.dev/docs/server/infra_tuning

Or maybe you are using join/leave messages which result into massive load in channels with many subscribers - https://centrifugal.dev/docs/4/faq#how-scalable-is-the-online-presence-and-joinleave-features so that your system can become overloaded.

Overall, there could be other reasons also, but it's impossible to help given the information you provided. Check out server logs, disconnect reasons, metrics. Make a reproducing scenario.

Also, I believe it's not related to `centrifuge-dart` - from client SDK perspective it's just a single connection which can't somehow affect other connections in such a way.

**Comment by FZambia** [comment] 2024-09-07 04:04
Closing, do not see nothing actionable here from `centrifuge-dart` perspective.

**Closed by FZambia** 2024-09-07 04:04 UTC
