### ISSUE TITLE
getting transport error on connect.

### ISSUE THREAD

**Issue by Tunmise-Adegoke** [centrifugal/centrifuge-dart#71] opened 2023-01-11 21:05 UTC
![centrihhj](https://user-images.githubusercontent.com/88061960/211912251-f53e6f66-80fc-44ef-b9a3-32042abd6057.png)
 
I tried connecting to a remote centrifugo deployment using the code above and got the error below,

![centrifugo](https://user-images.githubusercontent.com/88061960/211912465-eadaf617-ea7a-4045-aa32-cef67efa3fab.png)

 I want to add that this is the version of the dart package I'm using centrifuge: ^0.9.2 and the version of the remote deployment is 4.1.2

**Comment by FZambia** [comment] 2023-01-14 08:09
Hello @Tunmise-Adegoke 

How you are running it? Is it for web?

**Comment by Tunmise-Adegoke** [comment] 2023-01-15 12:03
Hello, I tried running it on mobile and I got a different error
![centri 2](https://user-images.githubusercontent.com/88061960/212539412-e7ed87bd-04c2-4c7b-a071-3b86e9e6d69d.png)

**Comment by FZambia** [comment] 2023-01-15 14:01
I see in the mobile logs that Centrifuge client successfully connected to the server and got unauthorized reason for subscription. Is that SocketException you observe raises from inside centrifuge-dart library? Or maybe its unrelated?

**Comment by Tunmise-Adegoke** [comment] 2023-01-15 15:13
I think it's from centrifugo because that's the only websocket on the app.

**Comment by FZambia** [comment] 2023-01-15 15:46
Can you check this? It may be from any other network activity I suppose - nothing in the exception says it's coming from the WebSocket. What's happening with the WebSocket connection after this error occurs btw?

**Comment by Tunmise-Adegoke** [comment] 2023-01-15 16:02
The websockets disconnects. I'm making some other network calls though but I don't think it should affect it. But the websocket disconnects after a minute.

**Comment by FZambia** [comment] 2023-01-15 16:13
If WebSocket disconnects a minute after being established this may be your proxy configuration which does not allow long-lived connections.

You may be right that the error comes from Centrifuge-dart. Or may be not. Since you have the reproducer you have all the power to check it. Or submit minimal reproducing steps without your app specifics so I could also take a closer look.

**Comment by Tunmise-Adegoke** [comment] 2023-01-17 10:55
This is my full code
tiny info I might add when connecting to the server through the centrifugo JS SDK it works well.
websocketurl =
      'ws://realtime.mize.app/connection/websocket?cf_protocol_version=v2'
![c1](https://user-images.githubusercontent.com/88061960/212881000-8a2416c5-6012-4229-8a6d-d47d6129d48f.png)
![c2](https://user-images.githubusercontent.com/88061960/212881016-d1b39eca-7b89-4be7-9546-0801a309723b.png)
![c3](https://user-images.githubusercontent.com/88061960/212881031-3d8205bb-4085-4fec-87f7-3f98876620a4.png)
![c4](https://user-images.githubusercontent.com/88061960/212881048-962724a8-b82b-4cf0-baa0-6ce12a27b7b9.png)

**Comment by FZambia** [comment] 2023-01-17 12:21
OMG, do you think I can run your screenshots?

Post the reproducing code as a repo on Github, give me instructions how to run it.

**Comment by Tunmise-Adegoke** [comment] 2023-01-18 14:08
Hello, This is a link to the repo I created
https://github.com/Tunmise-Adegoke/centrifugo_project
copy the code and clone it on your editor.
Make sure you have dart and flutter installed to run it then use an android emulator to run the app.

**Comment by FZambia** [comment] 2023-01-18 17:04
Hello @Tunmise-Adegoke 

Thanks for posting example, I managed to run it for both MacOS desktop app and in Android emulator. In both cases it works without any issues. And WebSocket connection not closed at all. Here is an output when running in Android emulator:

<img width="1534" alt="Screenshot 2023-01-18 at 19 00 34" src="https://user-images.githubusercontent.com/1196565/213246731-fc925ca6-24cf-4316-a24d-f518c6237f35.png">

```
❯ flutter --version
Flutter 3.3.10 • channel stable • ssh://git@github.com/flutter/flutter.git
Framework • revision 135454af32 (5 weeks ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0
```

**Comment by FZambia** [comment] 2023-01-20 07:17
@Tunmise-Adegoke any updates? do you see a different output when running on your machine? Have you tried to update flutter to the latest version?

**Comment by Tunmise-Adegoke** [comment] 2023-01-20 07:26
Hello@FZambia, I gave you an unlimited token which works perfectly on my own end too. I'm have been trying to generate a token from my api to test it. I have been getting errors so that's why I haven't replied since.

**Comment by Tunmise-Adegoke** [comment] 2023-01-21 14:16
Hello @FZambia, as seen in your screenshot, your event was unsubscribed for unauthorised reasons. I'm facing the same issue. Please do you know the reason?

**Comment by FZambia** [comment] 2023-01-21 17:32
Yes, the reason is that the code uses dummy getToken for Subscription: https://github.com/Tunmise-Adegoke/centrifugo_project/blob/f39da4727641f48e0b5b0d87b60ee6b0e8cffffb/lib/client/client.dart#L55

Instead of:

```dart
    final subscription = client.newSubscription(
      channel,
      centrifuge.SubscriptionConfig(
        getToken: (centrifuge.SubscriptionTokenEvent event) {
          return Future.value('');
        },
      ),
    );
```

You should use whether:

```dart
    final subscription = client.newSubscription(
      channel,
      centrifuge.SubscriptionConfig(),
    );
```

Or load subscription token properly (now returning `Future.value('');` in Subscription `getToken` tells SDK that client does not have permissions to subscribe on channel - this is described [here](https://centrifugal.dev/docs/transports/client_api#subscription-token)).

I can't say exactly which way you need – depends on server permission configuration.

**Comment by Tunmise-Adegoke** [comment] 2023-01-21 19:07
I tired another method apart from this and it worked. I can connect and subscribe with ease.

**Comment by FZambia** [comment] 2023-01-29 11:21
Closing – as far as I understand all is good here. BTW, centrifuge-dart SDK will also support web in the next release - was just added in #73 .

**Closed by FZambia** 2023-01-29 11:21 UTC

**Comment by Tunmise-Adegoke** [comment] 2023-01-29 11:34
Yay! For web.Thank you
